# Replace this file with your own paths!

# relative path to where data is saved
data_dir:
  dsads: "/home/gc28692/Projects/data/dsads"
  rwhar: "/home/gc28692/Projects/data/rwhar"

# relative path to where models, logs, and checkpoints will be saved
model_dir: "."