# Replace this file with your own paths!

# relative path to where data is saved
data_dir:
  dsads: "~/Projects/data/dsads"
  rwhar: "~/Projects/data/rwhar"

# relative path to where models, logs, and checkpoints will be saved
model_dir: "."